provider:
  linux: circle
  osx: travis
  win: appveyor
travis:
  secure:
    BINSTAR_TOKEN: odIF3g4yCFJfmjgvKuYCjIXzXNjDCUNisk7IFNjdau6+G1PYMOELjMEiNrZPtj2Uej1a6d6QQVj5wusmNvYzFvKmvWwxLp1t92Rh+qsHN5VGU6OLaIyPyVE25k+XExKK8b+6U3tMDPSHBQZguYHmY09eq3c/cCCpMa1VKuWobdTfewCrCd9rw9YN0qmJkXYs4I9qdeeJDroj/06yNt47+jEyId0rBK8qJaKmt4OhaGnPYr1LNVOEO6wFVFvaCKml/v/U6zAXJv/5y+YF1/0wOgLsUPqA0fZnTulqMn2COgZAMy2MvtMOEn0YPIsXfacUqSKT+VbrQ6kwDo41Kh9Rm/ubFiez9Zk2M8CXVOVVPwQQBoUhO++JN4sQ65GeRMZPzwEu6twjEIjuOWuun+s+hELFsdcGeVo79MjEHSd/QqoKgx9smd6wW0Aa74kqV9hJJeH5AXEWnuihgssbsY64zGjKTcY+Gd3Qg0jPIocoHKDnmEeEjmi0c5WqCqrrmzj0TTorJp0YZuBNaj7IveU+96grOVKwL+dtUMhzwGxhoZ+Vuid5uq87DumJ08pL9ps81OTevTdCCT2DhKCep0WPggU1O3VQkHczfOl29Lhr8XvQ3xMF6jKT12EPfZ+izSjqClmYn6MhT1BdLdRmmrpDbIz7jxMXXNyVRZd51VpjUP0=
appveyor:
  secure:
    BINSTAR_TOKEN: rUkm6Qxm7WeCOTtqaFwfM049EpNe1hrU1lV3fPadJTE2JmTH27x3XCjTNgRGSoCO
