travis:
  secure:
    BINSTAR_TOKEN: FDMJDwS92Hdqu8/XU6y4hPjmdY+ES1rx6BwAGF/UlKmDJcXCMxNktfsYGi1fIoJ+V7D/ciA7psgVZg6RyIqvOF+dOvEYwY6BnQ6SkqlJBrsnOoB6++62riULLAelCGhB8LWx09UaPqO7H4tZrISZFjveQA7x/5k3wMfPNIsrAnL3k1swi9Mzvq6PaDCl3F9+jBWgcpYyuLy+4gmuhDuj8mahNEHzjH+i4LoFYzFEOXWiUL0bn/BbjSzW5XO4V9hna/Crh6UfU2cdWrdfHDvubnL/vb5ZuNSHc8f1lAN03+KoTg+mGFTzjI2F9I8I7w8CKHCoankqXQ6KjDtrTu71dJnwopeZEqcynqR+sGsMWQlhy4CPSw/x/3B9kh/8BfeY0U/ldHvNfXTzlGSNS4J39u14NvmDTqqT7+bohUR4onJDIkuUCmC/BoWekcuRwpBGsJsngliveissBikEAQsSsafRBm1XtVAbLBAtA8dI61930p6xGbAVJOD19/Bfl1snJBZppVu/VFCjXyP2pfueglFIGo3mreM+oB8Uf/+40APk22w7ZB/Lay9sC9SQn77dzqRjnyvEbu0dSbVV+2gfCFG4mLKwDQ1y1beqrGqJoBtBaGHSEf+L75gIhPHNVmgRgWNo+d25XRIxmquvw7j2s/yVlreEiVLhDKUt7Ct4tUQ=
appveyor:
  secure:
    BINSTAR_TOKEN: 9O82YEDOL2SqS1j6GkDUQSmIVgF8OhykUw5LfD9c6zZgHfswA6L3Kfmup+h/JcAB
