travis:
  secure:
    BINSTAR_TOKEN: Y4C1D+DKePZwEC3z4JUJnHrwrW/PMlbI45LPQpYJuBbQrINZ/llPISbc8nnpGeBRO8XJWjQuO1uvYNFbB4vbGq2Be9gnvEKu8hd7D0rOoMUOBGMnc/4IIb5VJmfzCfpZYsklV91EF8QmIbv0jMgqdX06RN+MCJzpjBJsMDzg7vCf2rpWj6PFJnz34WD2jRXbND1NZ94F8RQpRlC7ZkySlyTMdN5+9ILiDTL1YYDMq8KCHR0O37kfXBM1ImI7dJbFefsqlj78iWrj7cdKdmc1wXlNGhfsnMdu0e/nREbg87nkobDlbHaD+D4+ZmbA6mmJ8jHdJ3c62Yty4XZsMAY4QzzeN0s05egWJL8RRUUQsvaUTUfH/qW2B3kcUx8w9DOhQ9tPe76WARufngbnxBLxKWxODigKWT8HN1/jk43siNKKwUq6QfUIDRpZI6KVr89lplgoAbgdmcnBrsCMXPKBn0EnVQgnjbP+rCBMKbSdO4P7POhY0wstVwNNcb0UywapOFx4IrkIic/5pVl/I92W8d9ZKIcacY3Nk6Q21ZPMLQDaFcMoKBaoKxbjGieDemdF/46zCDq4tSBv7t/TIB+I2GqT1p6PKZVZalP0LjiFtjTyYmPWPbTrGSOb51RtJfDQl3M1F4n976R//uIDsoq+Jx0yJD7nEKUseZ1mltGurso=
appveyor:
  secure:
    BINSTAR_TOKEN: 9O82YEDOL2SqS1j6GkDUQSmIVgF8OhykUw5LfD9c6zZgHfswA6L3Kfmup+h/JcAB
